title: Building a Thinking Classroom in Statistics and Data Science
description: Site for USCOTS 2025 Breakout Session
author: Nathan Kenny & Justin Post
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
